# mysql -h 0.0.0.0 -P 3000 --protocol=tcp -u root -p
# mysql --protocol=tcp -u root -p
version: "3.8"

networks:
  db-network:
    driver: bridge

volumes:
  db-mysql_data:
    driver: local

  php-my-admin-data:
    driver: local

services:
  mysql:
    platform: 'linux/x86_64'
    image: 'mysql:8'

    # reading MYSQL_CONTAINER_NAME from .env file
    container_name: '${MYSQL_CONTAINER_NAME}'

    # using cmd
    tty: true

    ports:
      - '${DB_PORT}:3306'

    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PWD}'
      # MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PWD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${MYSQL_ALLOW_EMPTY_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'

    volumes:
      - 'db-mysql_data:/var/lib/mysql/'

    networks:
      - db-network

  phpmyadmin:
    image: '${PMA_IMAGE}'
    container_name: '${PMA_CONTAINER_NAME}'
    environment:
      PMA_PMADB: 1
      PMA_ARBITARY: 1
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PWD}'

    restart: '${PMA_RESTART}'
    depends_on:
      - mysql
    ports:
      - '${PMA_PORT}:80'
    volumes:
      - 'php-my-admin-data:/etc/phpmyadmin/config.user.inc.php'
    networks:
      - db-network
    links:
      - mysql:db
