version: "3.8"

networks:
  my-network:
    external: true
    name: my-shared-network

# volumes:
#   php-my-admin-data:
#     driver: local

services:
  phpmyadmin:
    image: '${PMA_IMAGE}'
    container_name: '${PMA_CONTAINER_NAME}'
    environment:
      PMA_PMADB: 1
      PMA_ARBITARY: 1
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PWD}'

    restart: '${PMA_RESTART}'
    depends_on:
      - mysql
    ports:
      - '${PMA_PORT}:80'
    volumes:
      # volume
      # - 'php-my-admin-data:/etc/phpmyadmin/config.user.inc.php'

      # bind-mount
      - ./pma_data:/var/lib/mysql
    networks:
      - my-network
    links:
      - mysql:db
